### ISSUE TITLE
Call to undefined relationship [ignoredUsers] on model [Flarum\User\User].

### ISSUE THREAD

**Issue by supersonictw** [FriendsOfFlarum/ignore-users#5]
The bug occurs in `v0.1.0-beta.13`, the latest version of Flarum

**Comment by supersonictw** [comment]
Flarum will be dead while I enabling the plug-in.
It's a major error, hope to fix it, thank you.

**Comment by supersonictw** [comment]
I am sorry that I replied late but there is not any solution to resolve my problem directly, even I tried to fix but I couldn't understand the structure...So help needed...

![screenshot](https://ppt.cc/fwXQ6x@.png)

**Comment by supersonictw** [comment]
https://github.com/flarum/core/pull/2100
It seems `GetModelRelationship` has been deprecated even not working.

**Comment by karaok491** [comment]
Resolved `0.1.7`
